# HTTP filters
play.filters {
  # name of cookie in which the CSRF token is transmitted to client
  csrf.cookie.name = CYNOX-XSRF-TOKEN
  # name of header in which the client should send CSRD token
  csrf.header.name = X-CYNOX-XSRF-TOKEN

  enabled = [
  ]
}

play.http.parser.maxDiskBuffer = 128MB
play.http.parser.maxMemoryBuffer = 256kB


# Register module for dependency injection
play.modules.enabled += org.thp.cynox.CynoxModule

play.http.session.cookieName = CYNOX-SESSION

play.server.provider = org.thp.cynox.CustomAkkaHttpServerProvider

play.server.http.idleTimeout = 10 minutes

akka.actor {
  serializers {
    stream = "org.thp.cynox.services.StreamSerializer"
    notification = "org.thp.cynox.services.notification.NotificationSerializer"
    //cynox-schema-updater = "org.thp.cynox.models.SchemaUpdaterSerializer"
    flow = "org.thp.cynox.services.FlowSerializer"
    integrity = "org.thp.cynox.services.IntegrityCheckSerializer"
    caseNumber = "org.thp.cynox.services.CaseNumberSerializer"
  }

  serialization-bindings {
    "org.thp.cynox.services.StreamMessage" = stream
    "org.thp.cynox.services.notification.NotificationMessage" = notification
    //"org.thp.cynox.models.SchemaUpdaterMessage" = cynox-schema-updater
    "org.thp.cynox.services.FlowMessage" = flow
    "org.thp.cynox.services.IntegrityCheck$Message" = integrity
    "org.thp.cynox.services.CaseNumberActor$Message" = caseNumber
  }
}
